-- Seed: catalogo esercizi globale -> public.catalog_exercises
--
-- Sorgente dati: data/exercises.json (stessa identica lista, incollata qui sotto
-- come blocco JSON cosi' da poter eseguire il seed direttamente dal SQL Editor
-- di Supabase, senza CLI ne' service key).
--
-- Nomi in italiano (ricerca in app) + image_url reali dal dataset open-source
-- free-exercise-db (github.com/yuhonas/free-exercise-db, licenza pubblica).
--
-- Prerequisiti: aver applicato prima le migrazioni
--   supabase/migrations/20260708162000_initial_schema.sql
--   supabase/migrations/20260708170000_catalogs_and_nutrition.sql
--
-- Idempotente: la unique (source, source_id) fa upsert, quindi puoi rieseguirlo.

insert into public.catalog_exercises
  (source, source_id, name, description, category, equipment,
   primary_muscles, secondary_muscles, difficulty, image_url, video_url)
select
  e ->> 'source',
  e ->> 'source_id',
  e ->> 'name',
  e ->> 'description',
  e ->> 'category',
  e ->> 'equipment',
  coalesce(array(select jsonb_array_elements_text(e -> 'primary_muscles')), '{}'),
  coalesce(array(select jsonb_array_elements_text(e -> 'secondary_muscles')), '{}'),
  e ->> 'difficulty',
  e ->> 'image_url',
  e ->> 'video_url'
from jsonb_array_elements($seed$
[
  {"source":"seed","source_id":"barbell-bench-press","name":"Panca Piana con Bilanciere","description":"Lie on a flat bench and press a barbell from chest level to full arm extension.","category":"chest","equipment":"barbell","primary_muscles":["chest"],"secondary_muscles":["triceps","front deltoids"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg","video_url":null},
  {"source":"seed","source_id":"incline-dumbbell-press","name":"Panca Inclinata con Manubri","description":"Press two dumbbells upward on an inclined bench to target the upper chest.","category":"chest","equipment":"dumbbell","primary_muscles":["chest"],"secondary_muscles":["triceps","front deltoids"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg","video_url":null},
  {"source":"seed","source_id":"push-up","name":"Piegamenti sulle Braccia","description":"Lower and push your body up from the floor keeping a straight line from head to heels.","category":"chest","equipment":"bodyweight","primary_muscles":["chest"],"secondary_muscles":["triceps","core"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg","video_url":null},
  {"source":"seed","source_id":"cable-chest-fly","name":"Croci ai Cavi","description":"Bring two cable handles together in front of the chest with a slight elbow bend.","category":"chest","equipment":"cable","primary_muscles":["chest"],"secondary_muscles":["front deltoids"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg","video_url":null},
  {"source":"seed","source_id":"dips","name":"Dips alle Parallele","description":"Lower and press your body on parallel bars to work chest and triceps.","category":"chest","equipment":"bodyweight","primary_muscles":["chest","triceps"],"secondary_muscles":["front deltoids"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Chest_Version/0.jpg","video_url":null},
  {"source":"seed","source_id":"deadlift","name":"Stacco da Terra","description":"Lift a loaded barbell from the floor to hip level with a neutral spine.","category":"back","equipment":"barbell","primary_muscles":["erector spinae","glutes","hamstrings"],"secondary_muscles":["lats","forearms"],"difficulty":"advanced","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg","video_url":null},
  {"source":"seed","source_id":"pull-up","name":"Trazioni alla Sbarra","description":"Hang from a bar and pull your chin above it using the back muscles.","category":"back","equipment":"bodyweight","primary_muscles":["lats"],"secondary_muscles":["biceps","forearms"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg","video_url":null},
  {"source":"seed","source_id":"bent-over-barbell-row","name":"Rematore con Bilanciere","description":"Hinge at the hips and row a barbell to the lower ribcage.","category":"back","equipment":"barbell","primary_muscles":["lats","rhomboids"],"secondary_muscles":["biceps","rear deltoids"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg","video_url":null},
  {"source":"seed","source_id":"lat-pulldown","name":"Lat Machine Avanti","description":"Pull a cable bar down to the upper chest while seated.","category":"back","equipment":"cable","primary_muscles":["lats"],"secondary_muscles":["biceps"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg","video_url":null},
  {"source":"seed","source_id":"seated-cable-row","name":"Pulley Basso","description":"Pull a cable handle toward the torso while seated with a tall chest.","category":"back","equipment":"cable","primary_muscles":["lats","rhomboids"],"secondary_muscles":["biceps"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg","video_url":null},
  {"source":"seed","source_id":"barbell-back-squat","name":"Squat con Bilanciere","description":"Squat down and stand back up with a barbell resting on the upper back.","category":"legs","equipment":"barbell","primary_muscles":["quadriceps","glutes"],"secondary_muscles":["hamstrings","core"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Full_Squat/0.jpg","video_url":null},
  {"source":"seed","source_id":"romanian-deadlift","name":"Stacco Rumeno","description":"Hinge at the hips lowering a barbell along the legs to stretch the hamstrings.","category":"legs","equipment":"barbell","primary_muscles":["hamstrings","glutes"],"secondary_muscles":["erector spinae"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg","video_url":null},
  {"source":"seed","source_id":"leg-press","name":"Pressa per Gambe","description":"Push a loaded platform away with the legs on a seated machine.","category":"legs","equipment":"machine","primary_muscles":["quadriceps","glutes"],"secondary_muscles":["hamstrings"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg","video_url":null},
  {"source":"seed","source_id":"walking-lunge","name":"Affondi con Manubri","description":"Step forward into a lunge and continue walking, alternating legs.","category":"legs","equipment":"dumbbell","primary_muscles":["quadriceps","glutes"],"secondary_muscles":["hamstrings"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg","video_url":null},
  {"source":"seed","source_id":"leg-curl","name":"Leg Curl da Sdraiato","description":"Curl the heels toward the glutes against machine resistance.","category":"legs","equipment":"machine","primary_muscles":["hamstrings"],"secondary_muscles":["calves"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg","video_url":null},
  {"source":"seed","source_id":"leg-extension","name":"Leg Extension","description":"Extend the knees to lift a padded lever against machine resistance.","category":"legs","equipment":"machine","primary_muscles":["quadriceps"],"secondary_muscles":[],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg","video_url":null},
  {"source":"seed","source_id":"standing-calf-raise","name":"Calf in Piedi","description":"Rise onto the balls of the feet and lower under control.","category":"legs","equipment":"machine","primary_muscles":["calves"],"secondary_muscles":[],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg","video_url":null},
  {"source":"seed","source_id":"overhead-barbell-press","name":"Lento Avanti con Bilanciere","description":"Press a barbell from the shoulders to overhead while standing.","category":"shoulders","equipment":"barbell","primary_muscles":["shoulders"],"secondary_muscles":["triceps","core"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg","video_url":null},
  {"source":"seed","source_id":"dumbbell-lateral-raise","name":"Alzate Laterali","description":"Raise two dumbbells out to the sides to shoulder height.","category":"shoulders","equipment":"dumbbell","primary_muscles":["side deltoids"],"secondary_muscles":[],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg","video_url":null},
  {"source":"seed","source_id":"face-pull","name":"Face Pull","description":"Pull a rope toward the face with high elbows to target the rear delts.","category":"shoulders","equipment":"cable","primary_muscles":["rear deltoids"],"secondary_muscles":["traps"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg","video_url":null},
  {"source":"seed","source_id":"arnold-press","name":"Arnold Press","description":"Press dumbbells overhead while rotating the palms from facing in to facing out.","category":"shoulders","equipment":"dumbbell","primary_muscles":["shoulders"],"secondary_muscles":["triceps"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg","video_url":null},
  {"source":"seed","source_id":"barbell-biceps-curl","name":"Curl con Bilanciere","description":"Curl a barbell from the thighs to the shoulders keeping the elbows fixed.","category":"arms","equipment":"barbell","primary_muscles":["biceps"],"secondary_muscles":["forearms"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg","video_url":null},
  {"source":"seed","source_id":"dumbbell-hammer-curl","name":"Curl a Martello","description":"Curl dumbbells with a neutral grip to work biceps and forearms.","category":"arms","equipment":"dumbbell","primary_muscles":["biceps"],"secondary_muscles":["forearms"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg","video_url":null},
  {"source":"seed","source_id":"triceps-pushdown","name":"Pushdown ai Cavi","description":"Push a cable bar down by extending the elbows.","category":"arms","equipment":"cable","primary_muscles":["triceps"],"secondary_muscles":[],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg","video_url":null},
  {"source":"seed","source_id":"overhead-triceps-extension","name":"Estensioni Tricipiti in Piedi","description":"Extend a dumbbell overhead from behind the head to work the triceps.","category":"arms","equipment":"dumbbell","primary_muscles":["triceps"],"secondary_muscles":[],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Triceps_Extension/0.jpg","video_url":null},
  {"source":"seed","source_id":"preacher-curl","name":"Curl alla Panca Scott","description":"Curl a barbell with the upper arms supported on a preacher bench.","category":"arms","equipment":"barbell","primary_muscles":["biceps"],"secondary_muscles":["forearms"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg","video_url":null},
  {"source":"seed","source_id":"plank","name":"Plank","description":"Hold a straight body position on the forearms to brace the core.","category":"core","equipment":"bodyweight","primary_muscles":["core"],"secondary_muscles":["shoulders"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg","video_url":null},
  {"source":"seed","source_id":"hanging-leg-raise","name":"Sollevamento Gambe alla Sbarra","description":"Hang from a bar and raise the legs to hip height or higher.","category":"core","equipment":"bodyweight","primary_muscles":["abs"],"secondary_muscles":["hip flexors"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg","video_url":null},
  {"source":"seed","source_id":"cable-crunch","name":"Crunch ai Cavi","description":"Kneel and crunch the torso downward against cable resistance.","category":"core","equipment":"cable","primary_muscles":["abs"],"secondary_muscles":[],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg","video_url":null},
  {"source":"seed","source_id":"russian-twist","name":"Russian Twist","description":"Rotate the torso side to side while seated with the feet off the floor.","category":"core","equipment":"bodyweight","primary_muscles":["obliques"],"secondary_muscles":["abs"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg","video_url":null},
  {"source":"seed","source_id":"treadmill-running","name":"Corsa sul Tapis Roulant","description":"Run at a steady pace on a treadmill for cardiovascular conditioning.","category":"cardio","equipment":"machine","primary_muscles":["cardiovascular"],"secondary_muscles":["quadriceps","calves"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running_Treadmill/0.jpg","video_url":null},
  {"source":"seed","source_id":"rowing-machine","name":"Vogatore","description":"Drive with the legs and pull the handle to the ribs for full-body cardio.","category":"cardio","equipment":"machine","primary_muscles":["cardiovascular"],"secondary_muscles":["lats","quadriceps"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Stationary/0.jpg","video_url":null},
  {"source":"seed","source_id":"jumping-jacks","name":"Jumping Jacks","description":"Jump while spreading the legs and raising the arms overhead, then return.","category":"cardio","equipment":"bodyweight","primary_muscles":["cardiovascular"],"secondary_muscles":["calves"],"difficulty":"beginner","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Star_Jump/0.jpg","video_url":null},
  {"source":"seed","source_id":"kettlebell-swing","name":"Kettlebell Swing","description":"Hinge at the hips and swing a kettlebell to chest height using the glutes.","category":"cardio","equipment":"kettlebell","primary_muscles":["glutes","hamstrings"],"secondary_muscles":["cardiovascular","core"],"difficulty":"intermediate","image_url":"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Swings/0.jpg","video_url":null}
]
$seed$::jsonb) as e
on conflict (source, source_id) do update set
  name              = excluded.name,
  description       = excluded.description,
  category          = excluded.category,
  equipment         = excluded.equipment,
  primary_muscles   = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  difficulty        = excluded.difficulty,
  image_url         = excluded.image_url,
  video_url         = excluded.video_url,
  updated_at        = now();
